server:
  port: 8080

spring:
  application:
    name: accounts
  # as default behavior activate this profile
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8071/
